name: Generate singularity version

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Singularity version to build and upload (eg. 3.7.1)'
        required: true

env:
  VERSION: ${{ github.event.inputs.VERSION }}

jobs:
  build:
    name: Build Singularity ${{ github.event.inputs.VERSION }} [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    env:
      ARTIFACT_NAME: singularity-${{ github.event.inputs.VERSION }}-${{ matrix.os }}-x64
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: hpcng/singularity
          ref: v${{ env.VERSION }}
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.6'
      - name: Install OS deps
        run: sudo apt install uuid-dev
      - name: Build
        run: |
          ./mconfig --without-suid -p ${{ runner.tool_cache }}/singularity/${{ env.VERSION }}/x64
          cd builddir
          make -j 2
          make install
      - name: Echo version
        run: |
          ${{ runner.tool_cache }}/singularity/${{ env.VERSION }}/x64/bin/singularity --version
      - name: Make tarball
        run: |
          mkdir ${{ runner.temp }}/artifact
          tar -C ${{ runner.tool_cache }}/singularity/${{ env.VERSION }}/x64 -zcf ${{ runner.temp }}/artifact/${{ env.ARTIFACT_NAME }}.tar.gz .
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ runner.temp }}/artifact
  publish_release:
    name: Publish build tarballs in a release
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
    - name: Publish Release ${{ env.VERSION }}
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}-${{ github.run_id }}
        release_name: ${{ env.VERSION }}
        body: |
          Singularity v${{ env.VERSION }} for use in GH Actions
    - name: Upload release assets
      uses: actions/github-script@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          for (let artifactDir of fs.readdirSync('.')) {
            let artifactName = fs.readdirSync(`${artifactDir}`)[0];
            console.log(`Upload ${artifactName} asset`);
            github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ steps.create_release.outputs.id }},
              name: artifactName,
              data: fs.readFileSync(`./${artifactDir}/${artifactName}`)
            });
          }

  # TODO manually trigger create-pr wf first
  # trigger_pr:
  #   name: Trigger "Create Pull Request" workflow
  #   needs: publish_release
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Trigger "Create Pull Request" workflow
  #     uses: actions/github-script@v3
  #     with:
  #       # dispatch requires more scope/permision then secrets.GITHUB_TOKEN
  #       # See https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
  #       github-token: ${{ secrets.PERSONAL_TOKEN }}
  #       script: |
  #         github.actions.createWorkflowDispatch({
  #           owner: context.repo.owner,
  #           repo: context.repo.repo,
  #           workflow_id: 'create-pr.yml',
  #           ref: 'master'
  #         });
